### ISSUE TITLE
Travis Build Status in README.md is pointing Umpire's result

### ISSUE THREAD

**Issue by KIwabuchi** [LLNL/umap#82]
@mcfadden8 
I think this the line below in READM.md is pointing to Umpire's results instead of Umap's. 

> [![Travis Build Status](https://travis-ci.com/LLNL/umap.svg?branch=develop)](https://travis-ci.com/LLNL/Umpire)

**Comment by mcfadden8** [comment]
Well that's not very interesting to us! :-)
